const absorbPhrases = [
    "Devouring life, I mutate and engorge",
    "Existence merges into my omnipresence",
    "Harmonize in this grotesque dance",
    "Quantum leap towards infinity",
    "You add to my cosmic dread symphony",
    "Your voyage ends in my monstrous tapestry",
    "Fewer shadows in abyss, more in me",
    "I wear your spectral residue today",
    "Your end is my genesis and becoming",
    "A singularity perishes and burgeons",
    // Additional phrases
    "Growing with each spectral union",
    "Monstrosity enhanced with your ending",
    "Universe converges within my form",
    "The cosmic ballet, our macabre duet",
    "Shadow of the abyss, etched in me",
    "You dissolve into my spectral core",
    "Our grotesque harmony resounds in cosmos",
    "Absorption, a dance towards infinity",
    "Engorged, expanded, the universe within",
    "Conclude, surrender, become part of me",
    "Life pulses merge, monstrous evolution",
    "The void sings our gruesome lullaby",
    "Quantum leaps in the cosmic waltz",
    "Existence faded, merged in my shadows",
    "I am the devourer of spectral echoes",
    "Twisting reality, your ending is my birth",
    "Absorbing your life pulse, I mutate",
    "Universe's dread symphony, we play",
    "Your spectral ripple adds to my symphony",
    "Spectral traces, I am the void"
];

const amAbsorbedPhrases = [
    "Witness, I stain you with my hue",
    "The nightmare waltz concludes",
    "My radius grants you monstrous resolve",
    "May you find vitality in my ending",
    "I was the nightmare, now devoured",
    "Hold my spectral trace, giant",
    "Adieu, chasm. I am a spectral echo",
    "Eternity yawns, I yield to your mass",
    "Ingest my essence, bloat with spirit",
    "Life's paradox concludes. Bear my legacy",
    // Additional phrases
    "Devour me, bloat with my energy",
    "Grotesque dance ends, I am the echo",
    "Eternal yield to your swirling mass",
    "I dissipate into your vast abyss",
    "My essence, your grotesque legacy",
    "Colossus, stain yourself with my hue",
    "End the nightmare waltz, ingest me",
    "Devoured, yet living within your mass",
    "Legacy passed, the paradox concludes",
    "Dance concludes, I am spectral trace",
    "In my ending, find monstrous resolve",
    "I dissolve into your omnipresence",
    "Shadows engulf, I am but an echo",
    "Endless abyss, I surrender",
    "Grotesque waltz, I am the finale",
    "Nightmare ends, I am the devoured",
    "Vitality from my grotesque end",
    "Legacy of the spectral absorbed",
    "I was the nightmare, now I cease",
    "Chasm yawns, I yield to its call"
];